### ISSUE TITLE
Why ims.apk?

### ISSUE THREAD

**Issue by ynedelskiy** [PureNexusProject/proprietary_vendor_huawei#1]
Hi,
in this repo I see files:
/app/ims/ims.apk
/lib/libimscamera_jni.so
/lib/libimsmedia_jni.so
/lib64/libimscamera_jni.so
/lib64/libimsmedia_jni.so

It seems they were copied to 'proprietary_vendor_huawei' repo from the vendor.img file
from Angler's MHC19I factory image
dl.google.com/dl/android/aosp/angler-mhc19i-factory-fb2128bf.tgz

So I'm curious:
1) why they are included?
2) what is the function of ims.apk and relevant libraries?

**Comment by beanstown106** [comment]
when in the vendor.img they have a mismatched signature, but adding them to system with our signature "platform" allows the signature to match the system, and luckily android loads the ones in system before it loads the ones in vendor :)

**Comment by beanstown106** [comment]
sorry for late reply just saw
